spring:
  application:
    name: public-poject-bai
  datasource:
    url: jdbc:mysql://192.168.115.31:3306/campus_base?useUnicode=true&characterEncoding=UTF8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.115.31:8848
  jpa:
    show-sql: true

logging:
  level:
    com.xty.campus: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 9000
