spring:
  application:
    name: public-poject
  datasource:
    url: jdbc:mysql://192.168.115.31:3306/campus_base
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

